/*
 * File: app/store/Startlijst_VliegtuigenAanwezigGeweest_Store.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeZC_StartAdministratie.store.Startlijst_VliegtuigenAanwezigGeweest_Store', {
    extend: 'Ext.data.Store',

    requires: [
        'GeZC_StartAdministratie.model.Startlijst_Vliegtuigen_Model'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: false,
            autoSync: true,
            storeId: 'Startlijst_Vliegtuigenlijstkort_Store',
            model: 'GeZC_StartAdministratie.model.Startlijst_Vliegtuigen_Model',
            remoteSort: true,
            proxy: {
                type: 'ajax',
                simpleSortMode: true,
                url: 'php/main.php?Action=Aanwezig.VliegtuigenAanwezigJSON',
                reader: {
                    type: 'json',
                    idProperty: 'ID',
                    root: 'results'
                }
            },
            listeners: {
                load: {
                    fn: me.onJsonstoreLoad,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onJsonstoreLoad: function(store, records, successful, operation, options) {
        Ext.win.showLoading(false, store.storeId);
        this.laatsteAanpassingOpslaan();


        // Invoeren van het vliegtuig voor de start
        var InvoerVliegtuig = Ext.getCmp('StartInvoer.Vliegtuig');

        if (InvoerVliegtuig != undefined)
        {
            store.clearFilter();
            eval("var f =" + InvoerVliegtuig.primaryFilterBy);
            store.filterBy(f);
        }

    }

});
