/*
 * File: app/view/ControleTab.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeZC_StartAdministratie.view.ControleTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.controletab',

    requires: [
        'GeZC_StartAdministratie.view.ControleStartLiijstFlarmTab',
        'GeZC_StartAdministratie.view.ControleDagOverzichtTab',
        'GeZC_StartAdministratie.view.ExportTab',
        'GeZC_StartAdministratie.view.ControleTijdelijk',
        'Ext.tab.Panel',
        'Ext.grid.Panel',
        'Ext.tab.Tab'
    ],

    hidden: true,
    id: 'ControleTab',
    title: 'Controle',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    flex: 1,
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'ControleStartLiijstFlarmTab',
                            title: 'Startlijst - Flarm'
                        },
                        {
                            xtype: 'DagOverzichtTab'
                        },
                        {
                            xtype: 'exporttab',
                            title: 'Export'
                        },
                        {
                            xtype: 'controletijdelijk'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});