/*
 * File: app/view/ControleDetailsWindow.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeZC_StartAdministratie.view.ControleDetailsWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.ControleDetailsWindow',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View'
    ],

    height: 190,
    id: 'ControleDetailsWindow',
    width: 1167,
    title: 'My Window',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    id: 'ControleDetailsGrid',
                    enableColumnHide: false,
                    scroll: 'none',
                    store: 'ControleDagOverzichtLidStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 40,
                            defaultWidth: 40,
                            dataIndex: 'DAGNUMMER',
                            text: '#'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'REG_CALL',
                            text: 'Registratie'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'STARTMETHODE',
                            text: 'Start methode',
                            flex: 3
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 200,
                            dataIndex: 'VLIEGERNAAM',
                            text: 'Voorin'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 200,
                            dataIndex: 'INZITTENDENAAM',
                            text: 'Achterin'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 50,
                            dataIndex: 'STARTTIJD',
                            text: 'Start'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 50,
                            dataIndex: 'LANDINGSTIJD',
                            text: 'Landing'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 50,
                            dataIndex: 'DUUR',
                            text: 'Duur'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 200,
                            dataIndex: 'OP_REKENING',
                            text: 'Op rekening'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'SOORTVLUCHT',
                            text: 'Soort vlucht',
                            flex: 5
                        }
                    ],
                    listeners: {
                        itemdblclick: {
                            fn: me.onControleDetailsGridItemDblClick,
                            scope: me
                        }
                    }
                }
            ],
            listeners: {
                show: {
                    fn: me.onWindowShow,
                    scope: me
                },
                afterrender: {
                    fn: me.onControleDetailsWindowAfterRender,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onControleDetailsGridItemDblClick: function(dataview, record, item, index, e, eOpts) {
        Ext.Hoofdscherm.Startlijst_GridviewItemDblClick(dataview, record, item, index, e, eOpts);
    },

    onWindowShow: function(component, eOpts) {
        Ext.Controle.onControleDetailsWindowShow(component, eOpts, this.ID);
    },

    onControleDetailsWindowAfterRender: function(component, eOpts) {
        setTimeout(function()
                   {
                       var grid = Ext.getCmp('ControleDetailsGrid');
                       var win = Ext.getCmp('ControleDetailsWindow');

                       win.setHeight(grid.getHeight()+32);
                   },100);
    }

});