/*
 * File: app/view/CopyLandingstijdWindow.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeZC_StartAdministratie.view.CopyLandingstijdWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.CopyLandingstijdWindow',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.button.Button',
        'Ext.form.field.Text'
    ],

    height: 148,
    id: 'StarttijdWindow2',
    width: 274,
    resizable: false,
    title: 'Starttijd overnemen',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    primaryFilterOnKeyInput: 'true',
                    height: 115,
                    id: 'LandingCopyForm',
                    width: 265,
                    layout: 'absolute',
                    bodyPadding: 10,
                    title: '',
                    trackResetOnLoad: true,
                    url: 'php/main.php?Action=Controle.SaveLandingsTijd',
                    items: [
                        {
                            xtype: 'hiddenfield',
                            x: 35,
                            y: 210,
                            id: 'CopyLandingstijd_ID',
                            width: 50,
                            fieldLabel: '',
                            hideEmptyLabel: false,
                            labelWidth: 0,
                            name: 'ID'
                        },
                        {
                            xtype: 'button',
                            x: 75,
                            y: 40,
                            formBind: true,
                            height: 30,
                            id: 'LandingCopy_Overnemen',
                            width: 75,
                            text: 'Overnemen',
                            listeners: {
                                click: {
                                    fn: me.onLandingCopy_OvernemenClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            x: 170,
                            y: 65,
                            formBind: true,
                            height: 40,
                            id: 'LandingCopy_Opslaan',
                            width: 80,
                            text: 'Opslaan',
                            listeners: {
                                click: {
                                    fn: me.onLandingCopy_OpslaanClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 10,
                            id: 'LandingSA_Text',
                            width: 140,
                            fieldLabel: 'Landingstijd',
                            labelWidth: 60,
                            name: 'SA_LANDINGSTIJD',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 80,
                            id: 'LandingFlarm_Text',
                            width: 140,
                            fieldLabel: 'Flarm',
                            labelWidth: 60,
                            name: 'FLARM_LANDINGSTIJD',
                            readOnly: true
                        }
                    ]
                }
            ],
            listeners: {
                show: {
                    fn: me.onWindowShow,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onLandingCopy_OvernemenClick: function(button, e, eOpts) {
        Ext.Controle.onLandingCopy_OvernemenClick(button, e, eOpts);

        // Geeft de opslaan button een kleurtje op basis van de data velden
        Ext.AanpassenButtonOpslaan(Ext.getCmp('LandingCopyForm'), Ext.getCmp('LandingCopy_Opslaan'));
    },

    onLandingCopy_OpslaanClick: function(button, e, eOpts) {
        Ext.Controle.onLandingCopy_OpslaanClick(button, e, eOpts);
    },

    onWindowShow: function(component, eOpts) {
        Ext.Controle.onLandingCopyWindowShow(component, eOpts, this.ID);
    }

});