/*
 * File: app/view/DagInfoTab.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeZC_StartAdministratie.view.DagInfoTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.daginfotab',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea',
        'Ext.button.Button'
    ],

    id: 'Daginfo',
    itemId: '',
    collapsible: true,
    title: 'Daginfo',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    flex: 1,
                    disabled: true,
                    height: 393,
                    id: 'DaginfoForm',
                    bodyPadding: 10,
                    frameHeader: false,
                    title: '',
                    trackResetOnLoad: true,
                    url: 'php/main.php?Action=Daginfo.SaveObject',
                    waitTitle: 'Even wachten',
                    items: [
                        {
                            xtype: 'hiddenfield',
                            fieldLabel: 'Label',
                            name: 'ID'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            id: 'DagInfoDatum',
                            fieldLabel: 'Label',
                            name: 'DATUM'
                        },
                        {
                            xtype: 'panel',
                            border: 0,
                            margin: 10,
                            layout: 'table',
                            items: [
                                {
                                    xtype: 'panel',
                                    height: 95,
                                    margin: '0 10 0 0',
                                    width: 288,
                                    layout: 'absolute',
                                    title: 'Vliegveld',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            validator: function(value) {
                                                return Ext.Daginfo.ValiderenVliegveld(value);
                                            },
                                            x: -29,
                                            y: 10,
                                            id: 'ComboboxInfoVliegveld',
                                            width: 300,
                                            fieldLabel: 'Vliegveld',
                                            labelAlign: 'right',
                                            msgTarget: 'side',
                                            name: 'VELD_ID',
                                            allowBlank: false,
                                            displayField: 'OMSCHRIJVING',
                                            forceSelection: true,
                                            queryMode: 'local',
                                            store: 'Types_Vliegvelden_Store',
                                            typeAhead: true,
                                            valueField: 'ID',
                                            listeners: {
                                                render: {
                                                    fn: me.onComboboxInfoBanenRender1,
                                                    scope: me
                                                },
                                                change: {
                                                    fn: me.onComboboxInfoVliegveldChange,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'combobox',
                                            validator: function(value) {
                                                return Ext.Daginfo.ValiderenBaan(value);
                                            },
                                            x: -29,
                                            y: 40,
                                            id: 'ComboboxInfoBanen',
                                            width: 180,
                                            fieldLabel: 'Baan',
                                            labelAlign: 'right',
                                            msgTarget: 'side',
                                            name: 'BAAN_ID',
                                            displayField: 'OMSCHRIJVING',
                                            forceSelection: true,
                                            queryMode: 'local',
                                            store: 'Types_Banen_Store',
                                            typeAhead: true,
                                            valueField: 'ID',
                                            listeners: {
                                                render: {
                                                    fn: me.onComboboxInfoBanenRender,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    height: 95,
                                    id: 'WindPanel',
                                    width: 377,
                                    layout: 'absolute',
                                    title: 'Wind',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            validator: function(value) {
                                                return Ext.Daginfo.ValiderenWindrichting(value);
                                            },
                                            x: 0,
                                            y: 10,
                                            id: 'ComboboxInfoWindRichting',
                                            width: 275,
                                            fieldLabel: 'Richting',
                                            labelAlign: 'right',
                                            labelWidth: 75,
                                            msgTarget: 'side',
                                            name: 'WINDRICHTING_ID',
                                            displayField: 'OMSCHRIJVING',
                                            forceSelection: true,
                                            queryMode: 'local',
                                            store: 'Types_WindRichting_Store',
                                            typeAhead: true,
                                            valueField: 'ID',
                                            listeners: {
                                                render: {
                                                    fn: me.onComboboxInfoWindRichtingRender,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'combobox',
                                            validator: function(value) {
                                                return Ext.Daginfo.ValiderenWindkracht(value);
                                            },
                                            x: 0,
                                            y: 40,
                                            id: 'ComboboxInfoWindKracht',
                                            width: 275,
                                            fieldLabel: 'Kracht',
                                            labelAlign: 'right',
                                            labelWidth: 75,
                                            msgTarget: 'side',
                                            name: 'WINDKRACHT_ID',
                                            displayField: 'OMSCHRIJVING',
                                            forceSelection: true,
                                            queryMode: 'local',
                                            store: 'Types_WindKracht_Store',
                                            typeAhead: true,
                                            valueField: 'ID',
                                            listeners: {
                                                render: {
                                                    fn: me.onComboboxInfoWindKrachtRender,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            height: 102,
                            margin: 10,
                            width: 675,
                            layout: 'absolute',
                            title: 'Vliegbedrijf',
                            items: [
                                me.processComboboxInfoStartMethode({
                                    xtype: 'combobox',
                                    validator: function(value) {
                                        return Ext.Daginfo.ValiderenStartMethode(value);
                                    },
                                    primaryFilterOnKeyInput: 'true',
                                    x: 285,
                                    y: 10,
                                    id: 'ComboboxInfoStartMethode',
                                    width: 290,
                                    fieldLabel: 'Start methode',
                                    labelAlign: 'right',
                                    labelWidth: 90,
                                    msgTarget: 'side',
                                    name: 'STARTMETHODE_ID',
                                    matchFieldWidth: false,
                                    displayField: 'OMSCHRIJVING',
                                    forceSelection: true,
                                    queryMode: 'local',
                                    store: 'Types_StartMethode_Store',
                                    typeAhead: true,
                                    valueField: 'ID',
                                    listeners: {
                                        render: {
                                            fn: me.onComboboxInfoStartMethodeRender,
                                            scope: me
                                        }
                                    }
                                }),
                                {
                                    xtype: 'combobox',
                                    validator: function(value) {
                                        return Ext.Daginfo.ValiderenClub(value);
                                    },
                                    primaryFilterOnKeyInput: 'true',
                                    x: -29,
                                    y: 10,
                                    id: 'ComboboxInfoClub',
                                    width: 300,
                                    fieldLabel: 'Club',
                                    labelAlign: 'right',
                                    msgTarget: 'side',
                                    name: 'BEDRIJF_ID',
                                    allowBlank: false,
                                    matchFieldWidth: false,
                                    displayField: 'OMSCHRIJVING',
                                    forceSelection: true,
                                    queryMode: 'local',
                                    store: 'Types_Club_Store',
                                    typeAhead: true,
                                    valueField: 'ID',
                                    listeners: {
                                        render: {
                                            fn: me.onComboboxInfoStartMethodeRender1,
                                            scope: me
                                        },
                                        change: {
                                            fn: me.onComboboxInfoClubChange,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'combobox',
                                    validator: function(value) {
                                        return Ext.Daginfo.ValiderenSoortBedrijf(value);
                                    },
                                    primaryFilterOnKeyInput: 'true',
                                    x: -29,
                                    y: 40,
                                    id: 'ComboboxInfoSoortBedrijf',
                                    width: 300,
                                    fieldLabel: 'Bedrijf',
                                    labelAlign: 'right',
                                    msgTarget: 'side',
                                    name: 'SOORTBEDRIJF_ID',
                                    allowBlank: false,
                                    matchFieldWidth: false,
                                    displayField: 'OMSCHRIJVING',
                                    forceSelection: true,
                                    queryMode: 'local',
                                    store: 'Types_SoortBedrijf_Store',
                                    typeAhead: true,
                                    valueField: 'ID',
                                    listeners: {
                                        render: {
                                            fn: me.onComboboxInfoStartMethodeRender11,
                                            scope: me
                                        },
                                        change: {
                                            fn: me.onComboboxInfoSoortBedrijfChange,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            height: 130,
                            margin: 10,
                            width: 675,
                            layout: 'absolute',
                            title: 'Ochtend',
                            items: [
                                {
                                    xtype: 'textfield',
                                    x: -29,
                                    y: 10,
                                    id: 'TextboxInfoOchtendDDI',
                                    width: 300,
                                    fieldLabel: 'DDI',
                                    labelAlign: 'right',
                                    msgTarget: 'side',
                                    name: 'OCHTEND_DDI',
                                    selectOnFocus: true,
                                    listeners: {
                                        change: {
                                            fn: me.onTextboxInfoOchtendDDIChange,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    x: 300,
                                    y: 10,
                                    id: 'TextboxInfoOchtendInstructeur',
                                    width: 275,
                                    fieldLabel: 'Instructeur',
                                    labelAlign: 'right',
                                    labelWidth: 75,
                                    msgTarget: 'side',
                                    name: 'OCHTEND_INSTRUCTEUR',
                                    selectOnFocus: true,
                                    listeners: {
                                        change: {
                                            fn: me.onTextboxInfoOchtendInstructeurChange,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    x: -29,
                                    y: 40,
                                    id: 'TextboxInfoOchtendLierist',
                                    width: 300,
                                    fieldLabel: 'Lierist',
                                    labelAlign: 'right',
                                    msgTarget: 'side',
                                    name: 'OCHTEND_LIERIST',
                                    selectOnFocus: true,
                                    listeners: {
                                        change: {
                                            fn: me.onTextboxInfoOchtendLieristChange,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    x: 300,
                                    y: 40,
                                    id: 'TextboxInfoOchtendHulpLierist',
                                    width: 275,
                                    fieldLabel: 'Hulplierist',
                                    labelAlign: 'right',
                                    labelWidth: 75,
                                    msgTarget: 'side',
                                    name: 'OCHTEND_HULPLIERIST',
                                    selectOnFocus: true,
                                    listeners: {
                                        change: {
                                            fn: me.onTextboxInfoOchtendHulpLieristChange,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    x: -29,
                                    y: 70,
                                    id: 'TextboxInfoOchtendStartleider',
                                    width: 300,
                                    fieldLabel: 'Startleider',
                                    labelAlign: 'right',
                                    msgTarget: 'side',
                                    name: 'OCHTEND_STARTLEIDER',
                                    selectOnFocus: true,
                                    listeners: {
                                        change: {
                                            fn: me.onTextboxInfoOchtendStartleiderChange,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            height: 130,
                            hidden: true,
                            id: 'Daginfo_MiddagContainer',
                            margin: 10,
                            width: 675,
                            layout: 'absolute',
                            title: 'Middag',
                            items: [
                                {
                                    xtype: 'textfield',
                                    x: -28,
                                    y: 10,
                                    id: 'TextboxInfoMiddagDDI',
                                    width: 300,
                                    fieldLabel: 'DDI',
                                    labelAlign: 'right',
                                    msgTarget: 'side',
                                    name: 'MIDDAG_DDI',
                                    selectOnFocus: true,
                                    listeners: {
                                        change: {
                                            fn: me.onTextboxInfoMiddagDDIChange,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    x: 300,
                                    y: 10,
                                    id: 'TextboxInfoMiddagInstructeur',
                                    width: 275,
                                    fieldLabel: 'Instructeur',
                                    labelAlign: 'right',
                                    labelWidth: 75,
                                    msgTarget: 'side',
                                    name: 'MIDDAG_INSTRUCTEUR',
                                    selectOnFocus: true,
                                    listeners: {
                                        change: {
                                            fn: me.onTextboxInfoMiddagInstructeurChange,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    x: -28,
                                    y: 40,
                                    id: 'TextboxInfoMiddagLierist',
                                    width: 300,
                                    fieldLabel: 'Lierist',
                                    labelAlign: 'right',
                                    msgTarget: 'side',
                                    name: 'MIDDAG_LIERIST',
                                    selectOnFocus: true,
                                    listeners: {
                                        change: {
                                            fn: me.onTextboxInfoMiddagLieristChange,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    x: 300,
                                    y: 40,
                                    id: 'TextboxInfoMiddagHulpLierist',
                                    width: 275,
                                    fieldLabel: 'Hulplierist',
                                    labelAlign: 'right',
                                    labelWidth: 75,
                                    msgTarget: 'side',
                                    name: 'MIDDAG_HULPLIERIST',
                                    selectOnFocus: true,
                                    listeners: {
                                        change: {
                                            fn: me.onTextboxInfoMiddagHulpLieristChange,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    x: -28,
                                    y: 70,
                                    id: 'TextboxInfoMiddagStartleider',
                                    width: 300,
                                    fieldLabel: 'Startleider',
                                    labelAlign: 'right',
                                    msgTarget: 'side',
                                    name: 'MIDDAG_STARTLEIDER',
                                    selectOnFocus: true,
                                    listeners: {
                                        change: {
                                            fn: me.onTextboxInfoMiddagStartleiderChange,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            border: 0,
                            height: 120,
                            margin: 10,
                            width: 675,
                            layout: 'absolute',
                            frameHeader: false,
                            items: [
                                {
                                    xtype: 'textareafield',
                                    anchor: '100%',
                                    x: -29,
                                    y: 0,
                                    id: 'TextboxInfoOpmerkingen',
                                    maxWidth: 600,
                                    minWidth: 600,
                                    width: 600,
                                    fieldLabel: 'Opmerking',
                                    labelAlign: 'right',
                                    name: 'OPMERKINGEN'
                                },
                                {
                                    xtype: 'button',
                                    x: 590,
                                    y: 20,
                                    formBind: false,
                                    height: 40,
                                    id: 'OpslaanDaginfoButton',
                                    width: 80,
                                    text: 'Opslaan',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    x: 0,
                                    y: 35,
                                    height: 25,
                                    id: 'DagInfoRooster',
                                    icon: 'images/calendar.png',
                                    text: 'Rooster',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick3,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ],
                    listeners: {
                        afterrender: {
                            fn: me.onDaginfoFormAfterRender,
                            scope: me
                        }
                    }
                }
            ],
            listeners: {
                activate: {
                    fn: me.onDagInfoActivate,
                    scope: me
                },
                deactivate: {
                    fn: me.onDagInfoDeactivate,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    processComboboxInfoStartMethode: function(config) {
        config.plugins = ['clearbutton'];
        return config;
    },

    onComboboxInfoBanenRender1: function(component, eOpts) {
        Ext.QuickTips.register({
            target: component.getEl(),
            text: 'De baan waarop vandaag gestart wordt. Bij omstellen dit veld aanpassen.'
        });
    },

    onComboboxInfoVliegveldChange: function(field, newValue, oldValue, eOpts) {
        Ext.Daginfo.DynamischFormulier();
    },

    onComboboxInfoBanenRender: function(component, eOpts) {
        Ext.QuickTips.register({
            target: component.getEl(),
            text: 'De baan waarop vandaag gestart wordt. Bij omstellen dit veld aanpassen. Vul "-" in voor wanneer er niet op Terlet gevlogen wordt.'
        });
    },

    onComboboxInfoWindRichtingRender: function(component, eOpts) {
        Ext.QuickTips.register({
            target: component.getEl(),
            text: 'Bij benadering de windrichting.'
        });
    },

    onComboboxInfoWindKrachtRender: function(component, eOpts) {
          Ext.QuickTips.register({
            target: component.getEl(),
            text: 'Bij benadering de windkracht'
          });
    },

    onComboboxInfoStartMethodeRender: function(component, eOpts) {
        Ext.QuickTips.register({
            target: component.getEl(),
            text: 'De startmethode die voor de meeste vliegtuigen gebruikt wordt. Kan geduurende de dag veranderen.'
        });
    },

    onComboboxInfoStartMethodeRender1: function(component, eOpts) {
        Ext.QuickTips.register({
            target: component.getEl(),
            text: 'Welke club is verantwoordeijk voor het vliegbedrijf.'
        });
    },

    onComboboxInfoClubChange: function(field, newValue, oldValue, eOpts) {
        Ext.Daginfo.DynamischFormulier();
    },

    onComboboxInfoStartMethodeRender11: function(component, eOpts) {
        Ext.QuickTips.register({
            target: component.getEl(),
            text: 'Geef aan of we ook een DDWV bedrijf hebben.'
        });
    },

    onComboboxInfoSoortBedrijfChange: function(field, newValue, oldValue, eOpts) {
        Ext.Daginfo.DynamischFormulier();
    },

    onTextboxInfoOchtendDDIChange: function(field, newValue, oldValue, eOpts) {
        Ext.Daginfo.DynamischFormulier();
    },

    onTextboxInfoOchtendInstructeurChange: function(field, newValue, oldValue, eOpts) {
        Ext.Daginfo.DynamischFormulier();

    },

    onTextboxInfoOchtendLieristChange: function(field, newValue, oldValue, eOpts) {
        Ext.Daginfo.DynamischFormulier();

    },

    onTextboxInfoOchtendHulpLieristChange: function(field, newValue, oldValue, eOpts) {
        Ext.Daginfo.DynamischFormulier();

    },

    onTextboxInfoOchtendStartleiderChange: function(field, newValue, oldValue, eOpts) {
        Ext.Daginfo.DynamischFormulier();
    },

    onTextboxInfoMiddagDDIChange: function(field, newValue, oldValue, eOpts) {
        Ext.Daginfo.DynamischFormulier();
    },

    onTextboxInfoMiddagInstructeurChange: function(field, newValue, oldValue, eOpts) {
        Ext.Daginfo.DynamischFormulier();
    },

    onTextboxInfoMiddagLieristChange: function(field, newValue, oldValue, eOpts) {
        Ext.Daginfo.DynamischFormulier();
    },

    onTextboxInfoMiddagHulpLieristChange: function(field, newValue, oldValue, eOpts) {
        Ext.Daginfo.DynamischFormulier();
    },

    onTextboxInfoMiddagStartleiderChange: function(field, newValue, oldValue, eOpts) {
        Ext.Daginfo.DynamischFormulier();
    },

    onDaginfoFormAfterRender: function(component, eOpts) {
        Ext.getCmp('ComboboxInfoBanen').validate();
        Ext.getCmp('ComboboxInfoWindRichting').validate();
        Ext.getCmp('ComboboxInfoWindKracht').validate();
    },

    onButtonClick: function(button, e, eOpts) {
        Ext.Daginfo.onButtonClick(button, e, eOpts);

    },

    onButtonClick3: function(button, e, eOpts) {

        var view = Ext.widget('RoosterWindow');
        view.show();
    },

    onDagInfoActivate: function(component, eOpts) {
        InitStores();		// voor het geval dat de gebruiker eerder dit tab activeert dan dat de sores geladen zijn

        ComboBoxStartMethode = Ext.getCmp('ComboboxInfoStartMethode');

        ComboBoxStartMethode.primaryFilterBy =
        "function myfilter(record,id) " +
        "{" +
            "    if (record.data.ID == '501') return true;" +
            "    if (record.data.ID.substring(0,2) == '55') return true;" +
            "    return false;" +
        "}";

        ComboBoxStartMethode.store.clearFilter();
        eval("var f =" + ComboBoxStartMethode.primaryFilterBy)
        ComboBoxStartMethode.store.filterBy(f);
    },

    onDagInfoDeactivate: function(component, eOpts) {

        ComboBoxStartMethode = Ext.getCmp('ComboboxInfoStartMethode');
        ComboBoxStartMethode.primaryFilterBy = null;
        ComboBoxStartMethode.store.clearFilter();

    }

});