/*
 * File: app/view/DetailsPanel.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeZC_StartAdministratie.view.DetailsPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.DetailsPanel',

    requires: [
        'Ext.tree.Panel',
        'Ext.tree.View',
        'Ext.tree.Column',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.grid.View'
    ],

    height: 250,
    width: 400,
    collapseDirection: 'right',
    activeTab: 0,
    tabPosition: 'bottom',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    layout: 'fit',
                    collapseFirst: false,
                    title: 'Vliegers',
                    items: [
                        {
                            xtype: 'treepanel',
                            id: 'VliegersTreeView',
                            width: 300,
                            frameHeader: false,
                            title: '&nbsp;',
                            enableColumnHide: false,
                            enableColumnMove: false,
                            enableColumnResize: false,
                            forceFit: true,
                            hideHeaders: true,
                            sortableColumns: false,
                            store: 'StartLijst_VliegerTreeview_Store',
                            rootVisible: false,
                            viewConfig: {

                            },
                            columns: [
                                {
                                    xtype: 'treecolumn',
                                    dataIndex: 'TEXT',
                                    text: 'MyTreeColumn3',
                                    flex: 4
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'STARTTIJD',
                                    text: 'MyColumn207',
                                    flex: 1
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'DUUR',
                                    text: 'MyColumn208',
                                    flex: 1
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    layout: 'fit',
                    title: 'Club kisten',
                    items: [
                        {
                            xtype: 'panel',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'treepanel',
                                    flex: 3,
                                    id: 'ClubKistenTreeView',
                                    title: '&nbsp; ',
                                    enableColumnHide: false,
                                    enableColumnMove: false,
                                    enableColumnResize: false,
                                    forceFit: true,
                                    hideHeaders: true,
                                    sortableColumns: false,
                                    store: 'StartLijst_VliegtuigenTreeview_Store',
                                    rootVisible: false,
                                    viewConfig: {

                                    },
                                    columns: [
                                        {
                                            xtype: 'treecolumn',
                                            dataIndex: 'TEXT',
                                            text: 'MyTreeColumn1',
                                            flex: 3
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'VLUCHTEN',
                                            text: 'MyColumn87',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                var retVal = value;
                                                if (record.data.GEEN_LANDINGSTIJD > 0)
                                                {
                                                    retVal = '<IMG SRC="images/alert.gif" border=0>';
                                                    metaData.tdAttr = 'data-qtip="Er zijn nog vluchten die niet geland zijn"';
                                                }


                                                return retVal;
                                            },
                                            dataIndex: 'DUUR',
                                            text: 'MyColumn88',
                                            flex: 1
                                        }
                                    ],
                                    listeners: {
                                        select: {
                                            fn: me.onClubKistenTreeViewSelect,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    id: 'ClubKistenLogDetails',
                                    title: 'Logboek details',
                                    store: 'VliegtuigLogboek_Store',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'DATUM',
                                            text: 'Datum',
                                            flex: 2
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'VLUCHTEN',
                                            text: 'Vluchten',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'LIERSTARTS',
                                            text: 'Lier',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'SLEEPSTARTS',
                                            text: 'Sleep',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'VLIEGTIJD',
                                            text: 'Tijd',
                                            flex: 2
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onClubKistenTreeViewSelect: function(rowmodel, record, index, eOpts) {
                Ext.Hoofdscherm.ClubKistenTreeViewSelect(rowmodel, record, index, eOpts);
    }

});