/*
 * File: app/view/FlarmStartWindow.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeZC_StartAdministratie.view.FlarmStartWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.FlarmStartWindow',

    requires: [
        'Ext.form.Panel',
        'Ext.grid.Panel',
        'Ext.toolbar.Paging',
        'Ext.grid.View',
        'Ext.grid.column.Column',
        'Ext.form.field.Text'
    ],

    height: 641,
    width: 450,
    resizable: false,
    layout: 'fit',
    title: 'Flarm starts',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            listeners: {
                beforeshow: {
                    fn: me.onWindowBeforeShow,
                    scope: me
                }
            },
            items: [
                {
                    xtype: 'form',
                    id: 'FlarmStartWindow',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'gridpanel',
                            frameHeader: false,
                            title: '',
                            enableColumnMove: false,
                            enableColumnResize: false,
                            forceFit: true,
                            store: 'FlarmStart_Store',
                            dockedItems: [
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    width: 360,
                                    afterPageText: 'van {0}',
                                    beforePageText: 'Pagina',
                                    displayInfo: true,
                                    displayMsg: 'Weergave {0} - {1} tot {2}',
                                    emptyMsg: 'Geen data aanwezig',
                                    firstText: 'Eerste pagina',
                                    lastText: 'Laatste pagina',
                                    nextText: 'Volgende pagina',
                                    prevText: 'Vorige pagina',
                                    refreshText: 'Verversen',
                                    store: 'FlarmStart_Store'
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'bottom',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'ZoekenFlarmStart',
                                            maxWidth: 200,
                                            minWidth: 200,
                                            width: 100,
                                            fieldLabel: 'Zoeken',
                                            labelAlign: 'right',
                                            labelWidth: 70,
                                            size: 5,
                                            listeners: {
                                                change: {
                                                    fn: me.onZoekenFlarmStartChange,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                }
                            ],
                            viewConfig: {
                                emptyText: '<div class="noData" ></div>'
                            },
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'REG_CALL',
                                    text: 'Vliegtuig',
                                    flex: 5
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'FLARM_CODE',
                                    text: 'Flarm',
                                    flex: 4
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'STARTTIJD',
                                    text: 'Start',
                                    flex: 3
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'LANDINGSTIJD',
                                    text: 'Landing',
                                    flex: 3
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'BAAN',
                                    text: 'Baan',
                                    flex: 2
                                }
                            ],
                            listeners: {
                                itemdblclick: {
                                    fn: me.onGridpanelItemDblClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onWindowBeforeShow: function(component, eOpts) {

        var store = Ext.data.StoreManager.lookup('FlarmStart_Store');
        store.proxy.extraParams =
        {
            '_:query': ""
        }
        store.load();
    },

    onZoekenFlarmStartChange: function(field, newValue, oldValue, eOpts) {
        var store = Ext.data.StoreManager.lookup('FlarmStart_Store');

        store.proxy.extraParams =
        {
            '_:query': Ext.getCmp('ZoekenFlarmStart').getValue()
        }
        store.loadPage(1);
    },

    onGridpanelItemDblClick: function(dataview, record, item, index, e, eOpts) {
        var appSettingsStore = Ext.data.StoreManager.lookup('AppSettings_Store');
        var appSettings = appSettingsStore.getAt(0);
        if (appSettings.data.isBeheerder)
        {
            Ext.FlarmForm.FlarmStart_GridviewItemClick(dataview, record, item, index, e, eOpts);
        }
    }

});