/*
 * File: app/view/Hoofscherm.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeZC_StartAdministratie.view.Hoofscherm', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.Hoofdscherm',

    requires: [
        'GeZC_StartAdministratie.view.StartlijstTab',
        'GeZC_StartAdministratie.view.DagInfoTab',
        'GeZC_StartAdministratie.view.AanwezigTab',
        'GeZC_StartAdministratie.view.LedenTab',
        'GeZC_StartAdministratie.view.VliegtuigenTab',
        'GeZC_StartAdministratie.view.KaartTab',
        'GeZC_StartAdministratie.view.ControleTab',
        'Ext.panel.Panel',
        'Ext.tab.Tab'
    ],

    hidden: true,
    id: 'HoofdScherm',
    itemId: '',
    hideCollapseTool: true,
    activeTab: 0,
    maxTabWidth: 90,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            listeners: {
                resize: {
                    fn: me.onHoofdSchermResize,
                    scope: me
                }
            },
            items: [
                {
                    xtype: 'StartlijstTab'
                },
                {
                    xtype: 'daginfotab'
                },
                {
                    xtype: 'aanwezigtab'
                },
                {
                    xtype: 'ledentab'
                },
                {
                    xtype: 'vliegtuigentab'
                },
                {
                    xtype: 'kaarttab'
                },
                {
                    xtype: 'controletab'
                }
            ]
        });

        me.callParent(arguments);
    },

    onHoofdSchermResize: function(component, adjWidth, adjHeight, eOpts) {
        Ext.Hoofdscherm.CalcStarlijstGrid();
        Ext.Hoofdscherm.CalcLedenGrid();
        Ext.Hoofdscherm.CalcVliegtuigenGrid();
        Ext.Hoofdscherm.CalcControleGrid();
    }

});