/*
 * File: app/view/LidBeheerWindow.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeZC_StartAdministratie.view.LidBeheerWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.LidBeheerWindow',

    requires: [
        'Ext.Img',
        'Ext.form.Label',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Checkbox',
        'Ext.button.Button',
        'Ext.form.field.Hidden'
    ],

    id: 'LidBeheerWindow',
    width: 400,
    resizable: false,
    title: 'Lid beheer',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    baseCls: 'title',
                    height: 48,
                    layout: 'table',
                    title: '',
                    items: [
                        {
                            xtype: 'image',
                            src: 'images/user_add.png'
                        },
                        {
                            xtype: 'label',
                            cls: 'titel',
                            frame: true,
                            id: 'LidBeheer_Titel',
                            padding: '10px',
                            text: 'Nieuw lid'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    id: 'LidBeheerForm',
                    bodyPadding: 10,
                    frameHeader: false,
                    title: '',
                    trackResetOnLoad: true,
                    url: 'php/main.php?Action=Leden.SaveObject',
                    items: [
                        me.processLidBeheer_Naam({
                            xtype: 'textfield',
                            anchor: '100%',
                            id: 'LidBeheer_Naam',
                            width: 375,
                            fieldLabel: 'Naam',
                            labelAlign: 'right',
                            labelWidth: 80,
                            msgTarget: 'side',
                            name: 'NAAM',
                            allowBlank: false,
                            blankText: 'Vul de naam van het lid in.',
                            maxLength: 30,
                            maxLengthText: 'De naam mag niet langer zijn dan 30 tekens',
                            minLength: 5,
                            minLengthText: 'De naam moet minimaal 5 tekens bevatten'
                        }),
                        me.processLidBeheer_Telefoon({
                            xtype: 'textfield',
                            validator: function(value) {
                                return Ext.LidBeheer.ValiderenTelefoonNummer(value);

                            },
                            anchor: '100%',
                            id: 'LidBeheer_Telefoon',
                            width: 370,
                            fieldLabel: 'Telefoon',
                            labelAlign: 'right',
                            labelWidth: 80,
                            msgTarget: 'side',
                            name: 'TELEFOON',
                            maxLength: 13,
                            maxLengthText: 'Het telefoonnummer mag maximaal 13 cijfers bevatten'
                        }),
                        me.processLidBeheer_Mobiel({
                            xtype: 'textfield',
                            validator: function(value) {
                                return Ext.LidBeheer.ValiderenTelefoonNummer(value);
                            },
                            anchor: '100%',
                            id: 'LidBeheer_Mobiel',
                            width: 370,
                            fieldLabel: 'Mobiel',
                            labelAlign: 'right',
                            labelWidth: 80,
                            msgTarget: 'side',
                            name: 'MOBIEL',
                            maxLength: 13,
                            maxLengthText: 'Het telefoonnummer mag maximaal 13 cijfers bevatten'
                        }),
                        {
                            xtype: 'combobox',
                            validator: function(value) {
                                return Ext.LidBeheer.ValiderenLidType(value);
                            },
                            primaryFilterOnKeyInput: 'false',
                            hidden: true,
                            id: 'LidBeheer_Lidtype',
                            width: 365,
                            fieldLabel: 'Lid type',
                            labelAlign: 'right',
                            labelWidth: 80,
                            msgTarget: 'side',
                            name: 'LIDTYPE_ID',
                            tabIndex: 40,
                            vtypeText: 'Invullen wie de rekening betaald',
                            displayField: 'OMSCHRIJVING',
                            forceSelection: true,
                            queryMode: 'local',
                            store: 'Types_Lid_Store',
                            typeAhead: true,
                            valueField: 'ID',
                            listeners: {
                                change: {
                                    fn: me.onLidBeheer_LidtypeChange,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            hidden: true,
                            id: 'LidBeheer_Code',
                            fieldLabel: 'Code',
                            labelAlign: 'right',
                            labelWidth: 80,
                            name: 'CODE'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            hidden: true,
                            id: 'LidBeheer_LidNr',
                            fieldLabel: 'Lid nummer',
                            labelAlign: 'right',
                            labelWidth: 80,
                            name: 'LIDNR'
                        },
                        {
                            xtype: 'checkboxfield',
                            anchor: '100%',
                            hidden: true,
                            id: 'LidBeheer_HeeftBetaald',
                            fieldLabel: 'Betaald',
                            labelAlign: 'right',
                            labelWidth: 80,
                            name: 'HEEFT_BETAALD',
                            boxLabel: '',
                            inputValue: '1',
                            uncheckedValue: '0'
                        },
                        {
                            xtype: 'button',
                            formBind: false,
                            height: 40,
                            id: 'InvoerenLid_Opslaan',
                            margin: '0px 285px',
                            padding: '',
                            width: 80,
                            text: 'Opslaan',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick1,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            fieldLabel: 'Label',
                            name: 'ID'
                        }
                    ],
                    listeners: {
                        afterrender: {
                            fn: me.onLidBeheerFormAfterRender,
                            scope: me
                        }
                    }
                }
            ],
            listeners: {
                show: {
                    fn: me.onLidBeheerWindowShow,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    processLidBeheer_Naam: function(config) {
        config.plugins = ['clearbutton'];
        return config;
    },

    processLidBeheer_Telefoon: function(config) {
        config.plugins = ['clearbutton'];
        return config;
    },

    processLidBeheer_Mobiel: function(config) {
        config.plugins = ['clearbutton'];
        return config;
    },

    onLidBeheer_LidtypeChange: function(field, newValue, oldValue, eOpts) {
        Ext.LidBeheer.onLidBeheer_LidtypeChange(field, newValue, oldValue, eOpts);
    },

    onButtonClick1: function(button, e, eOpts) {

        var form = Ext.getCmp('LidBeheerForm');
        var valid = form.getForm().isValid();

        if (!valid)
        {
            Ext.MessageBox.show({
                title: 'Onvolledige invoer',
                msg: 'Niet alle velden zijn correct ingevoerd',
                buttons: Ext.MessageBox.OK,
                icon:  Ext.MessageBox.WARNING
            });
            return;
        }

        Ext.getCmp('InvoerenLid_Opslaan').disable();
        Ext.win.showSaving(true);

        form.getForm().submit
        ({
            success: function(req,res)
            {
                Ext.win.showSaving(false);
                Ext.win.msg("Lid is opgeslagen");

                store = Ext.data.StoreManager.lookup('LedenLijst_GridStore');
                store.load();
                button.up('.window').close();

                // als we aangeroepen zijn door het start invoer scherm moeten we de gezagvoerder aanpassen
                var InvoerGezagvoerder = Ext.getCmp('StartInvoer_Gezagvoerder');
                if (InvoerGezagvoerder != null)
                {
                    InvoerGezagvoerder.store.load(
                    {
                        params:
                        {
                            '_:VliegerID': res.result.ID
                        },
                        scope : this,
                        callback: function(records, operation, success)
                        {
                            if(success)
                            {
                                InvoerGezagvoerder.setValue(res.result.ID.toString());
                            }
                        }
                    });

                }
            },
            failure: function(req,res)
            {
                Ext.win.showSaving(false);

                if (res.response.status == 200)
                Ext.MessageBox.alert ('Fout bij opslaan', res.result.error);
                else
                Ext.MessageBox.alert ('Server fout', res.response.responseText);

                button.up('.window').close();
            }
        });
    },

    onLidBeheerFormAfterRender: function(component, eOpts) {
        var form = Ext.getCmp('LidBeheerForm');
        var valid = form.getForm().isValid();
    },

    onLidBeheerWindowShow: function(component, eOpts) {
        Ext.LidBeheer.onLidBeheerWindowShow(component, eOpts, this.ID);
    }

});