/*
 * File: app/view/LidVandaagAanwezigWindow.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeZC_StartAdministratie.view.LidVandaagAanwezigWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.LidVandaagAanwezigWindow',

    requires: [
        'Ext.Img',
        'Ext.form.Label',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.selection.CheckboxModel',
        'Ext.button.Button'
    ],

    width: 414,
    resizable: false,
    frameHeader: false,
    title: 'Aanmelden vandaag',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    baseCls: 'title',
                    height: 48,
                    id: 'headerAanmelden',
                    layout: 'table',
                    title: '',
                    items: [
                        {
                            xtype: 'image',
                            src: 'images/user_add.png'
                        },
                        {
                            xtype: 'label',
                            cls: 'titel',
                            frame: true,
                            id: 'LidAanmelden_Titel',
                            padding: '10px',
                            text: 'Aanmelden vandaag'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    autoRender: true,
                    height: '',
                    id: 'LidAanmeldInvoerForm',
                    bodyPadding: 10,
                    trackResetOnLoad: true,
                    url: 'php/main.php?Action=Aanwezig.AanmeldenLidJSON',
                    items: [
                        {
                            xtype: 'combobox',
                            id: 'Aanmelden.VliegerCombobox',
                            width: 335,
                            fieldLabel: 'Vlieger',
                            labelAlign: 'right',
                            labelWidth: 85,
                            name: 'LID_ID',
                            displayField: 'NAAM',
                            queryMode: 'local',
                            store: 'Startlijst_Vlieger_Store',
                            valueField: 'ID',
                            listeners: {
                                change: {
                                    fn: me.onVliegerComboboxChange,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'combobox',
                            id: 'Aanwezig_InvoerVliegtuigID',
                            width: 210,
                            fieldLabel: 'Overland',
                            labelAlign: 'right',
                            labelWidth: 85,
                            name: 'VOORKEUR_VLIEGTUIG_ID',
                            displayField: 'REG_CALL',
                            forceSelection: true,
                            queryMode: 'local',
                            store: 'Startlijst_Vliegtuigen_Store',
                            valueField: 'ID'
                        },
                        {
                            xtype: 'label',
                            id: 'LabelVliegtuigType',
                            width: 85,
                            text: 'Vliegtuig type'
                        },
                        {
                            xtype: 'gridpanel',
                            id: 'Aanwezig_InvoerTypeVliegtuig',
                            minHeight: 100,
                            padding: '0 0 0 35',
                            bodyStyle: 'border: 0px;',
                            frameHeader: false,
                            enableColumnHide: false,
                            enableColumnMove: false,
                            enableColumnResize: false,
                            hideHeaders: true,
                            scroll: 'none',
                            sortableColumns: false,
                            store: 'Types_VliegtuigType_Store',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    cls: 'AITV-grid',
                                    dataIndex: 'OMSCHRIJVING',
                                    hideable: false,
                                    flex: 1
                                }
                            ],
                            viewConfig: {
                                cls: 'AITV-grid',
                                margin: '0px 0px 0px 50px',
                                stripeRows: false
                            },
                            selModel: Ext.create('Ext.selection.CheckboxModel', {

                            }),
                            listeners: {
                                selectionchange: {
                                    fn: me.onAanwezigInvoerTypeVliegtuigSelectionChange,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            width: 325,
                            fieldLabel: 'Opmerkingen',
                            labelAlign: 'right',
                            labelWidth: 85,
                            name: 'OPMERKING'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            hidden: true,
                            id: 'Aanmelden_VliegtuigTypeID',
                            hideLabel: true,
                            name: 'VOORKEUR_VLIEGTUIG_TYPE',
                            readOnly: true
                        },
                        {
                            xtype: 'button',
                            height: 40,
                            id: 'Opslaan_AanwezigButton',
                            margin: '0px 285px',
                            width: 80,
                            text: 'Opslaan',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ],
            listeners: {
                show: {
                    fn: me.onWindowShow,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onVliegerComboboxChange: function(field, newValue, oldValue, eOpts) {
        Ext.AanmeldenForm.onVliegerComboboxChange(field, newValue, oldValue, eOpts);
    },

    onAanwezigInvoerTypeVliegtuigSelectionChange: function(model, selected, eOpts) {
        Ext.AanmeldenForm.onStartInvoer_VliegtuigTypeSelectionChange(model, selected, eOpts);

    },

    onButtonClick: function(button, e, eOpts) {
        Ext.AanmeldenForm.onButtonClick(button, e, eOpts);
    },

    onWindowShow: function(component, eOpts) {
        Ext.AanmeldenForm.onInvoerWindowShow(component, eOpts, this.ID, this.LID_ID);
    }

});