/*
 * File: app/view/LinkFlarmStartWindow.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeZC_StartAdministratie.view.LinkFlarmStartWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.LinkFlarmStartWindow',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.view.BoundList',
        'Ext.XTemplate',
        'Ext.button.Button',
        'Ext.form.field.Hidden'
    ],

    height: 262,
    width: 408,
    resizable: false,
    layout: 'fit',
    title: 'Koppelen Flarm start',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    id: 'LinkFlarmStartForm',
                    layout: 'absolute',
                    bodyPadding: 10,
                    url: '/php/main.php?Action=Flarm.UpdateFlarmCode',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            cls: '',
                            id: 'REGCALL',
                            maxWidth: 220,
                            minWidth: 220,
                            width: 220,
                            fieldLabel: 'Vliegtuig',
                            labelAlign: 'right',
                            name: 'REG_CALL',
                            fieldStyle: 'font-weight:bold;font-size: 12px;',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            x: 10,
                            y: 40,
                            id: 'FLARM_CODE',
                            maxWidth: 180,
                            minWidth: 180,
                            width: 180,
                            fieldLabel: 'Flarm code',
                            labelAlign: 'right',
                            name: 'FLARM_CODE',
                            fieldStyle: 'font-weight:bold;font-size: 12px;',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            x: 10,
                            y: 70,
                            id: 'STARTTIJD',
                            fieldLabel: 'Start',
                            labelAlign: 'right',
                            name: 'STARTTIJD',
                            fieldStyle: 'font-weight:bold;font-size: 12px;',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            x: 10,
                            y: 100,
                            id: 'LANDINGSTIJD',
                            fieldLabel: 'Landing',
                            labelAlign: 'right',
                            name: 'LANDINGSTIJD',
                            fieldStyle: 'font-weight:bold;font-size: 12px;',
                            readOnly: true
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            x: 10,
                            y: 130,
                            fieldLabel: 'Nieuw vliegtuig',
                            labelAlign: 'right',
                            name: 'NIEUW_VLIEGTUIG_ID',
                            displayField: 'REGCALL',
                            store: 'StartLijstVoorFlarm_Store',
                            valueField: 'VLIEGTUIG_ID',
                            listConfig: {
                                xtype: 'boundlist',
                                itemSelector: 'div',
                                itemTpl: [
                                    '<table',
                                    '    <tpl for=".">',
                                    '        <tr>',
                                    '			<td width="20px">{DAGNUMMER}</td>',
                                    '			<td width="100px">{REGCALL}</td>',
                                    '			<td width="80px">{STARTTIJD}</td>',
                                    '			<td width="80px">{LANDINGSTIJD}</td>',
                                    '		</tr>',
                                    '    </tpl>',
                                    '</table>',
                                    ''
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            x: 295,
                            y: 170,
                            height: 40,
                            width: 80,
                            text: 'Opslaan',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'hiddenfield',
                            width: 100,
                            fieldLabel: 'Label',
                            name: 'VLIEGTUIG_ID'
                        },
                        {
                            xtype: 'hiddenfield',
                            fieldLabel: 'Label',
                            name: 'DATUM'
                        }
                    ]
                }
            ],
            listeners: {
                show: {
                    fn: me.onWindowShow,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        Ext.FlarmForm.onButtonClick(button, e, eOpts);
    },

    onWindowShow: function(component, eOpts) {

        var form = Ext.getCmp("LinkFlarmStartForm");
        var fs = Ext.data.StoreManager.lookup('FlarmStart_Store');
        var record = fs.getById(this.ID);


        form.getForm().loadRecord(record);


        var store = Ext.data.StoreManager.lookup('StartLijstVoorFlarm_Store');
        store.proxy.extraParams =
        {
            '_:starttijd': record.data.STARTTIJD,
            '_:landingstijd': record.data.LANDINGSTIJD
        }
        store.load();


    }

});