/*
 * File: app/view/LogboekWindow.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeZC_StartAdministratie.view.LogboekWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.LogboekWindow',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.Date',
        'Ext.form.field.Hidden',
        'Ext.resizer.Splitter',
        'Ext.button.Button',
        'Ext.grid.column.Number'
    ],

    height: 271,
    id: 'LogboekWindow',
    width: 581,
    layout: 'fit',
    title: 'Logboek',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    store: 'VliegtuigLogboek_Store',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'datefield',
                                    id: 'LogboekDatumVanaf',
                                    width: 150,
                                    fieldLabel: 'Vanaf',
                                    labelAlign: 'right',
                                    labelWidth: 40,
                                    listeners: {
                                        change: {
                                            fn: me.onLogboekDatumVanafChange,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'datefield',
                                    id: 'LogboekDatumTot',
                                    width: 150,
                                    fieldLabel: 'T/m',
                                    labelAlign: 'right',
                                    labelWidth: 40,
                                    listeners: {
                                        change: {
                                            fn: me.onLogboekDatumTotChange,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'hiddenfield',
                                    id: 'LogboekVliegtuigID',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'splitter',
                                    flex: 1
                                },
                                {
                                    xtype: 'button',
                                    width: 75,
                                    icon: 'images/list.png',
                                    text: 'Totaal',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ],
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'DATUM',
                            text: 'Datum'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'VLUCHTEN',
                            text: 'Totaal starts',
                            format: '0'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                if (value == 0)
                                return "";
                                else
                                return value;
                            },
                            dataIndex: 'LIERSTARTS',
                            text: 'Lier starts'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                if (value == 0)
                                return "";
                                else
                                return value;
                            },
                            dataIndex: 'SLEEPSTARTS',
                            text: 'Sleep starts'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                return value.substring(0,5);
                            },
                            dataIndex: 'VLIEGTIJD',
                            text: 'Vliegtijd'
                        }
                    ]
                }
            ],
            listeners: {
                afterrender: {
                    fn: me.onLogboekWindowAfterRender,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onLogboekDatumVanafChange: function(field, newValue, oldValue, eOpts) {
        Ext.data.StoreManager.lookup('VliegtuigLogboek_Store').load();
    },

    onLogboekDatumTotChange: function(field, newValue, oldValue, eOpts) {
        Ext.data.StoreManager.lookup('VliegtuigLogboek_Store').load();
    },

    onButtonClick: function(button, e, eOpts) {
                var store = Ext.data.StoreManager.lookup('VliegtuigLogboek_Store');
                var totaalTijd = 0, totaalLier=0, totaalSleep=0;

                store.each(function(r)
                {
                    totaalLier = totaalLier + r.data.LIERSTARTS*1;
                    totaalSleep = totaalSleep + r.data.SLEEPSTARTS*1;

                    totaalTijd = totaalTijd + r.data.VLIEGTIJD.substring(0,2)*60 + r.data.VLIEGTIJD.substring(3,5)*1;
                });

        var msgStr = sprintf("<table><col width='100'><tr><td>Aantal vluchten </td><td>:</td><td align='right'>%d</td><tr><tr><td>Aantal lierstarts </td><td>:</td><td align='right'>%d</td><tr><tr><td>Aantal sleepstarts </td><td>:</td><td align='right'>%d</td><tr><tr><td>Totale vliegtijd </td><td>:</td><td align='right'>%02d:%02d</td></tr></table>",
                                totaalLier+totaalSleep,
                                totaalLier,
                                totaalSleep,
                                totaalTijd/60,
                                totaalTijd%60);

                Ext.MessageBox.alert ("Logboek totaal", msgStr);
    },

    onLogboekWindowAfterRender: function(component, eOpts) {
        Ext.getCmp('LogboekVliegtuigID').setValue(this.ID);
        Ext.data.StoreManager.lookup('VliegtuigLogboek_Store').load();
    }

});