/*
 * File: app/view/RoosterWindow.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeZC_StartAdministratie.view.RoosterWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.RoosterWindow',

    requires: [
        'Ext.Img',
        'Ext.form.Label',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    id: 'RoosterWindow',
    width: 656,
    resizable: false,
    title: 'Rooster',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    baseCls: 'title',
                    height: 48,
                    layout: 'table',
                    title: '',
                    items: [
                        {
                            xtype: 'image',
                            src: 'images/rooster.png'
                        },
                        {
                            xtype: 'label',
                            cls: 'titel',
                            frame: true,
                            id: 'Rooster_Titel',
                            padding: '10px',
                            text: 'Rooster'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    id: 'RoosterForm',
                    bodyPadding: 10,
                    frameHeader: false,
                    title: '',
                    items: [
                        {
                            xtype: 'panel',
                            height: 130,
                            margin: 10,
                            width: 606,
                            layout: 'absolute',
                            title: 'Ochtend',
                            items: [
                                {
                                    xtype: 'textfield',
                                    x: -29,
                                    y: 10,
                                    disabled: true,
                                    disabledCls: 'x-item',
                                    id: 'TextboxRoosterOchtendDDI',
                                    width: 300,
                                    fieldLabel: 'DDI',
                                    labelAlign: 'right',
                                    msgTarget: 'side',
                                    name: 'OCHTEND_DDI',
                                    selectOnFocus: true
                                },
                                {
                                    xtype: 'button',
                                    x: 280,
                                    y: 10,
                                    id: 'ButtonCopyOchtendDDI',
                                    width: 20,
                                    icon: 'images/ictxt.gif',
                                    text: '',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonCopyOchtendDDIClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    x: 300,
                                    y: 10,
                                    disabled: true,
                                    disabledCls: 'x-item',
                                    id: 'TextboxRoosterOchtendInstructeur',
                                    width: 270,
                                    fieldLabel: 'Instructeur',
                                    labelAlign: 'right',
                                    labelWidth: 75,
                                    name: 'OCHTEND_INSTRUCTEUR',
                                    selectOnFocus: true
                                },
                                {
                                    xtype: 'button',
                                    x: 580,
                                    y: 10,
                                    id: 'ButtonCopyOchtendInstructeur',
                                    width: 20,
                                    icon: 'images/ictxt.gif',
                                    text: '',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonCopyOchtendInstructeurClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    x: -29,
                                    y: 40,
                                    disabled: true,
                                    disabledCls: 'x-item',
                                    id: 'TextboxRoosterOchtendLierist',
                                    width: 300,
                                    fieldLabel: 'Lierist',
                                    labelAlign: 'right',
                                    name: 'OCHTEND_LIERIST',
                                    selectOnFocus: true
                                },
                                {
                                    xtype: 'button',
                                    x: 280,
                                    y: 40,
                                    id: 'ButtonCopyOchtendLierist',
                                    width: 20,
                                    icon: 'images/ictxt.gif',
                                    text: '',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonCopyOchtendLieristClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    x: 300,
                                    y: 40,
                                    disabled: true,
                                    disabledCls: 'x-item',
                                    id: 'TextboxRoosterOchtendHulpLierist',
                                    width: 270,
                                    fieldLabel: 'Hulplierist',
                                    labelAlign: 'right',
                                    labelWidth: 75,
                                    name: 'OCHTEND_HULPLIERIST',
                                    selectOnFocus: true
                                },
                                {
                                    xtype: 'button',
                                    x: 580,
                                    y: 40,
                                    id: 'ButtonCopyOchtendHulpLierist',
                                    width: 20,
                                    icon: 'images/ictxt.gif',
                                    text: '',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonCopyOchtendHulpLieristClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    x: -29,
                                    y: 70,
                                    disabled: true,
                                    disabledCls: 'x-item',
                                    id: 'TextboxRoosterOchtendStartleider',
                                    width: 300,
                                    fieldLabel: 'Startleider',
                                    labelAlign: 'right',
                                    name: 'OCHTEND_STARTLEIDER',
                                    selectOnFocus: true
                                },
                                {
                                    xtype: 'button',
                                    x: 280,
                                    y: 70,
                                    id: 'ButtonCopyOchtendStartleider',
                                    width: 20,
                                    icon: 'images/ictxt.gif',
                                    text: '',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonCopyOchtendStartleiderClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            height: 130,
                            margin: 10,
                            width: 607,
                            layout: 'absolute',
                            title: 'Middag',
                            items: [
                                {
                                    xtype: 'textfield',
                                    x: -28,
                                    y: 10,
                                    disabled: true,
                                    disabledCls: 'x-item',
                                    id: 'TextboxRoosterMiddagDDI',
                                    width: 300,
                                    fieldLabel: 'DDI',
                                    labelAlign: 'right',
                                    msgTarget: 'side',
                                    name: 'MIDDAG_DDI',
                                    selectOnFocus: true
                                },
                                {
                                    xtype: 'button',
                                    x: 280,
                                    y: 10,
                                    id: 'ButtonCopyMiddagDDI',
                                    width: 20,
                                    icon: 'images/ictxt.gif',
                                    text: '',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonCopyMiddagDDIClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    x: 300,
                                    y: 10,
                                    disabled: true,
                                    disabledCls: 'x-item',
                                    id: 'TextboxRoosterMiddagInstructeur',
                                    width: 270,
                                    fieldLabel: 'Instructeur',
                                    labelAlign: 'right',
                                    labelWidth: 75,
                                    name: 'MIDDAG_INSTRUCTEUR',
                                    selectOnFocus: true
                                },
                                {
                                    xtype: 'button',
                                    x: 280,
                                    y: 40,
                                    id: 'ButtonCopyMiddagLierist',
                                    width: 20,
                                    icon: 'images/ictxt.gif',
                                    text: '',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonCopyMiddagLieristClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    x: -28,
                                    y: 40,
                                    disabled: true,
                                    disabledCls: 'x-item',
                                    id: 'TextboxRoosterMiddagLierist',
                                    width: 300,
                                    fieldLabel: 'Lierist',
                                    labelAlign: 'right',
                                    name: 'MIDDAG_LIERIST',
                                    selectOnFocus: true
                                },
                                {
                                    xtype: 'button',
                                    x: 280,
                                    y: 70,
                                    id: 'ButtonCopyMiddagStartleider',
                                    width: 20,
                                    icon: 'images/ictxt.gif',
                                    text: '',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonCopyMiddagStartleiderClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    x: 300,
                                    y: 40,
                                    disabled: true,
                                    disabledCls: 'x-item',
                                    id: 'TextboxRoosterMiddagHulpLierist',
                                    width: 270,
                                    fieldLabel: 'Hulplierist',
                                    labelAlign: 'right',
                                    labelWidth: 75,
                                    name: 'MIDDAG_HULPLIERIST',
                                    selectOnFocus: true
                                },
                                {
                                    xtype: 'button',
                                    x: 580,
                                    y: 10,
                                    id: 'ButtonCopyMiddagInstructeur',
                                    width: 20,
                                    icon: 'images/ictxt.gif',
                                    text: '',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonCopyMiddagInstructeurClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    x: -28,
                                    y: 70,
                                    disabled: true,
                                    disabledCls: 'x-item',
                                    id: 'TextboxRoosterMiddagStartleider',
                                    width: 300,
                                    fieldLabel: 'Startleider',
                                    labelAlign: 'right',
                                    name: 'MIDDAG_STARTLEIDER',
                                    selectOnFocus: true
                                },
                                {
                                    xtype: 'button',
                                    x: 580,
                                    y: 40,
                                    id: 'ButtonCopyMiddagHulpLierist',
                                    width: 20,
                                    icon: 'images/ictxt.gif',
                                    text: '',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonCopyMiddagHulpLieristClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ],
            listeners: {
                show: {
                    fn: me.onRoosterWindowShow,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onButtonCopyOchtendDDIClick: function(button, e, eOpts) {
        Ext.getCmp('TextboxInfoOchtendDDI').setValue(Ext.getCmp('TextboxRoosterOchtendDDI').getValue());
    },

    onButtonCopyOchtendInstructeurClick: function(button, e, eOpts) {
        Ext.getCmp('TextboxInfoOchtendInstructeur').setValue(Ext.getCmp('TextboxRoosterOchtendInstructeur').getValue());
    },

    onButtonCopyOchtendLieristClick: function(button, e, eOpts) {
        Ext.getCmp('TextboxInfoOchtendLierist').setValue(Ext.getCmp('TextboxRoosterOchtendLierist').getValue());
    },

    onButtonCopyOchtendHulpLieristClick: function(button, e, eOpts) {
        Ext.getCmp('TextboxInfoOchtendHulpLierist').setValue(Ext.getCmp('TextboxRoosterOchtendHulpLierist').getValue());
    },

    onButtonCopyOchtendStartleiderClick: function(button, e, eOpts) {
        Ext.getCmp('TextboxInfoOchtendStartleider').setValue(Ext.getCmp('TextboxRoosterOchtendStartleider').getValue());
    },

    onButtonCopyMiddagDDIClick: function(button, e, eOpts) {
        Ext.getCmp('TextboxInfoMiddagDDI').setValue(Ext.getCmp('TextboxRoosterMiddagDDI').getValue());
    },

    onButtonCopyMiddagLieristClick: function(button, e, eOpts) {
        Ext.getCmp('TextboxInfoMiddagLierist').setValue(Ext.getCmp('TextboxRoosterMiddagLierist').getValue());
    },

    onButtonCopyMiddagStartleiderClick: function(button, e, eOpts) {
        Ext.getCmp('TextboxInfoMiddagStartleider').setValue(Ext.getCmp('TextboxRoosterMiddagStartleider').getValue());
    },

    onButtonCopyMiddagInstructeurClick: function(button, e, eOpts) {
        Ext.getCmp('TextboxInfoMiddagInstructeur').setValue(Ext.getCmp('TextboxRoosterMiddagInstructeur').getValue());
    },

    onButtonCopyMiddagHulpLieristClick: function(button, e, eOpts) {
        Ext.getCmp('TextboxInfoMiddagHulpLierist').setValue(Ext.getCmp('TextboxRoosterMiddagHulpLierist').getValue());
    },

    onRoosterWindowShow: function(component, eOpts) {
        console.log(sprintf("%s: onRoosterWindowShow()", TijdStempel()));

        var store = Ext.data.StoreManager.lookup('Rooster_Store');
        store.load(
        {
            callback: function(records, operation, success)	// Deze functie wordt aangeroepen zodra de data van de server terug
            {
                if(!success)
                {
                    Ext.MessageBox.alert ('Fout bij ophalen data', operation.response.responseText);
                }
                else
                {
                    var store = Ext.data.StoreManager.lookup('Rooster_Store');

                    if (store.getCount() > 0)
                    {
                        var record = store.getAt(0);

                        var form = Ext.getCmp('RoosterForm');
                        form.loadRecord(record); 		// laad het record in het formulier
                    }
                }
            }
        });
    }

});