/*
 * File: app/view/StarttijdWindow.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeZC_StartAdministratie.view.StarttijdWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.StarttijdWindow',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    height: 100,
    id: 'StarttijdWindow',
    width: 300,
    resizable: false,
    title: 'Starttijd invoeren',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    primaryFilterOnKeyInput: 'true',
                    height: 66,
                    id: 'StartInvoer_StarttijdForm',
                    width: 288,
                    layout: 'absolute',
                    bodyPadding: 10,
                    title: '',
                    trackResetOnLoad: true,
                    url: 'php/main.php?Action=Startlijst.SaveStartTijd',
                    items: [
                        {
                            xtype: 'hiddenfield',
                            x: 35,
                            y: 210,
                            id: 'StartInvoerStarttijd_ID',
                            width: 50,
                            fieldLabel: '',
                            hideEmptyLabel: false,
                            labelWidth: 0,
                            name: 'ID'
                        },
                        {
                            xtype: 'hiddenfield',
                            id: 'StartInvoer_LandingsTijd',
                            fieldLabel: 'Label',
                            name: 'LANDINGSTIJD'
                        },
                        me.processStartInvoer_StartTijd({
                            xtype: 'combobox',
                            validator: function(value) {
                                // voer dit script uit om te zien of alles goed is ingevuld
                                return Ext.StartlijstTijdenForm.ValidateStartTijd(value);
                            },
                            formBind: true,
                            id: 'StartInvoer_StartTijd',
                            width: 140,
                            fieldLabel: 'Start',
                            labelAlign: 'right',
                            labelWidth: 50,
                            msgTarget: 'side',
                            name: 'STARTTIJD',
                            invalidText: 'Er is een ongeldige tijd ingevoerd',
                            emptyText: 'uu:mm',
                            enableKeyEvents: true,
                            enforceMaxLength: true,
                            maxLength: 5,
                            maxLengthText: 'Tijd formaat bestaat uit UU:MM',
                            size: 8,
                            displayField: 'tijd',
                            forceSelection: true,
                            queryDelay: 100,
                            queryMode: 'local',
                            valueField: 'tijd',
                            listeners: {
                                keypress: {
                                    fn: me.onStartInvoer_StartTijdKeypress,
                                    scope: me
                                },
                                change: {
                                    fn: me.onStartInvoer_StartTijdChange,
                                    scope: me
                                },
                                specialkey: {
                                    fn: me.onStartInvoer_StartTijdSpecialkey,
                                    scope: me
                                },
                                select: {
                                    fn: me.onStartInvoer_StartTijdSelect,
                                    scope: me
                                }
                            }
                        }),
                        {
                            xtype: 'button',
                            x: 190,
                            y: 10,
                            formBind: true,
                            height: 40,
                            id: 'StartInvoerStarttijd_Opslaan',
                            width: 80,
                            text: 'Opslaan',
                            listeners: {
                                click: {
                                    fn: me.onButtonStarttijdOpslaan,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ],
            listeners: {
                show: {
                    fn: me.onWindowShow,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    processStartInvoer_StartTijd: function(config) {
        // Toon in het invoerveld een kruisje om het veld met 1 muisklik leeg te maken
        config.plugins = ['clearbutton'];
        return config;
    },

    onStartInvoer_StartTijdKeypress: function(textfield, e, eOpts) {

        // iemand heeft een toets op het toetsenbord ingedrukt
        // alleen cijfers, backspace en delete zijn toegestaan
        if (e.getKey() != Ext.EventObject.BACKSPACE && e.getKey() != Ext.EventObject.DELETE)
        {
            if (e.getKey() > 57 || e.getKey() < 48)
            {
                e.stopEvent();
                return false;
            }
        }

        // als er goede toets is ingedrukt, voer het volgende script uit.
        Ext.StartlijstTijdenForm.onStartInvoer_Keypress(textfield, e, eOpts);
    },

    onStartInvoer_StartTijdChange: function(field, newValue, oldValue, eOpts) {

        // de tijd is gewijzigd. Voer het script uit.
        Ext.StartlijstTijdenForm.onChangeTijd(field);
    },

    onStartInvoer_StartTijdSpecialkey: function(field, e, eOpts) {
        // als de gebruiker de ENTER toets indrukt, dan slaan we de tijd op
        if(e.getKey() == Ext.EventObject.ENTER)
        {
            Ext.StartlijstTijdenForm.SaveStartTijd(field);
        }
        else
        {
            // het was dus niet de ENTER toets, maar een andere speciale toets
            Ext.StartlijstTijdenForm.onStartInvoer_Keypress(field, e, eOpts);
        }
    },

    onStartInvoer_StartTijdSelect: function(combo, records, eOpts) {
        // we zetten nu een variable zodat we het veld niet meer automatisch voorzien van de actuele tijd
        combo.manualInput = true;
    },

    onButtonStarttijdOpslaan: function(button, e, eOpts) {
        // voer dit script uit om de tijd op te slaan in de database
        Ext.StartlijstTijdenForm.SaveStartTijd(button, e, eOpts);
    },

    onWindowShow: function(component, eOpts) {
        Ext.StartlijstTijdenForm.onStarttijdWindowShow(component, eOpts, this.ID);
    }

});