/*
 * File: app/view/StartVerwijderWindow.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeZC_StartAdministratie.view.StartVerwijderWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.StartVerwijderWindow',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.form.field.Hidden'
    ],

    ID: -1,
    id: 'StartVerwijderWindow',
    width: 443,
    title: 'Start gegevens',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    autoRender: true,
                    id: 'StartVerwijder_VerwijderForm',
                    bodyPadding: 10,
                    frameHeader: false,
                    title: '',
                    url: 'php/main.php?Action=Startlijst.VerwijderObject',
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'StartVerwijder_Opmerking',
                            width: 375,
                            fieldLabel: 'Opmerking',
                            labelAlign: 'right',
                            labelWidth: 85,
                            msgTarget: 'side',
                            name: 'OPMERKING',
                            allowBlank: false,
                            blankText: 'Er moet een reden ingevoerd worden',
                            listeners: {
                                specialkey: {
                                    fn: me.onStartVerwijder_OpmerkingSpecialkey,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            formBind: true,
                            height: 40,
                            id: 'StartVerwijder_Verwijder',
                            margin: '0px 295px',
                            padding: '',
                            width: 80,
                            icon: 'images/delete.png',
                            text: 'Verwijderen',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'hiddenfield',
                            id: 'StartVerwijder_ID',
                            width: 50,
                            fieldLabel: '',
                            hideEmptyLabel: false,
                            labelWidth: 0,
                            name: 'ID'
                        }
                    ]
                }
            ],
            listeners: {
                show: {
                    fn: me.onStartVerwijderWindowShow,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onStartVerwijder_OpmerkingSpecialkey: function(field, e, eOpts) {
        if(e.getKey() == Ext.EventObject.ENTER)
        {
            var button = Ext.getCmp('StartVerwijder_Verwijder');
            Ext.StartlijstVerwijderForm.onButtonClick(button, null, null);
        }
    },

    onButtonClick: function(button, e, eOpts) {
        Ext.StartlijstVerwijderForm.onButtonClick(button, e, eOpts);
    },

    onStartVerwijderWindowShow: function(component, eOpts) {
        Ext.StartlijstVerwijderForm.onStartVerwijderWindowShow(component, eOpts, this.ID);
    }

});