/*
 * File: app/view/WorkspaceStartAdmin.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeZC_StartAdministratie.view.WorkspaceStartAdmin', {
    extend: 'Ext.container.Viewport',

    requires: [
        'GeZC_StartAdministratie.view.Hoofscherm',
        'Ext.form.field.Date',
        'Ext.tab.Panel'
    ],

    id: 'Workspace',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    region: 'north',
                    html: '<div id="header" style="background: url(images/header_bg.png);">\n<div style="height:70px; background:url(images/middleheader_gezc.jpg) no-repeat top right">\n<table width="100%" border="0" cellpadding="0" cellspacing="0">\n<tbody>\n<tr height="10" valign="top"><td rowspan=2 height="10" width="50">&nbsp;</td><td></td></tr>\n<tr height="60" valign="top"> \n\n<td height="60"> \n<IMG SRC="images/digit0.png" border=0 name="hourstens">\n<IMG SRC="images/digit0.png" border=0 name="hoursones">\n<IMG SRC="images/digitcolon.png" border=0 name="colon">\n<IMG SRC="images/digit0.png" border=0 name="minstens">\n<IMG SRC="images/digit0.png" border=0 name="minsones">\n</td>\n\n\n<td rowspan=2 height="70" width="300" align="center" valign="left" nowrap >\n<img src="images/tekst_gezc.gif" alt="Gelderse Logo"/>\n<font color="#FFFFFF" size="+1"><br><b>De Gelderse Zweefvliegclub</b></font></td>\n</tr> \n</tbody>\n</table>\n</div>\n</div>\n\n<div id="statusArea">\n<table border="0">\n<tr>\n<td>\n<a href=javascript:OpenCommStatusWindow();>\n<IMG name="commStatus" SRC="images/unknown.gif" border=0">\n</a>\n</td>\n\n<td width="200px" nowrap style="text-align: left; vertical-align: top;">\n<a href=javascript:OpenCommStatusWindow();>\n<div id="statusText" style="margin-left: 10px; link">Communicatie status onbekend</div>\n</a>\n</td>\n<td>\n<IMG name="flarmStatus" SRC="images/unknown.gif" border=0">\n</td>\n<td width="200px" nowrap style="text-align: left; vertical-align: top;">\n<a href=javascript:OpenFlarmStartWindow();>\n<div id="flarmText" style="margin-left: 10px; link">Flarm status onbekend</div>\n</a>\n</td> \n</tr>\n</table>\n</div>\n<div id="flarmArea">\n<table border="0">\n<tr>\n<td width="200px" nowrap style="text-align: left; vertical-align: top;">\n<a href=javascript:OpenFlarmStartWindow();>\n<div id="flarmText" style="margin-left: 10px; link">Flarm starts</div>\n</a>\n</td> \n</tr>\n</table>\n</div>',
                    id: 'Header',
                    style: 'Header style'
                },
                {
                    xtype: 'container',
                    region: 'west',
                    autoShow: true,
                    floating: true,
                    id: 'DatumExport',
                    maxHeight: 50,
                    maxWidth: 350,
                    minHeight: 50,
                    minWidth: 350,
                    width: 150,
                    shadow: false,
                    layout: 'absolute',
                    items: [
                        {
                            xtype: 'datefield',
                            x: 0,
                            y: 5,
                            hidden: true,
                            id: 'StartlijstDatum',
                            maxWidth: 200,
                            minWidth: 200,
                            width: 150,
                            fieldLabel: 'Datum',
                            labelAlign: 'right',
                            invalidText: '{value} De datum is ongeldig. Het formaat moet voldoen aan {format}',
                            enableKeyEvents: true,
                            format: 'd-m-Y',
                            listeners: {
                                change: {
                                    fn: me.onStarlijstDatumChange,
                                    scope: me
                                },
                                keydown: {
                                    fn: me.onStarlijstDatumKeydown,
                                    scope: me
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'Hoofdscherm',
                    region: 'center'
                }
            ],
            listeners: {
                afterrender: {
                    fn: me.onWorkspaceAfterRender,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onStarlijstDatumChange: function(field, newValue, oldValue, eOpts) {
        var  store;

        store = Ext.data.StoreManager.lookup('Startlijst_GridStore');
        Ext.win.showLoading(true, store.storeId);
        store.load();

        store = Ext.data.StoreManager.lookup('Daginfo_Store');
        Ext.win.showLoading(true, store.storeId);
        store.load(
            {
                callback: function(records, operation, success)	// Deze functie wordt aangeroepen zodra de data van de server terug
                {
                    if(success)
                    {
                        var di = Ext.data.StoreManager.lookup('Daginfo_Store');
                        var daginfo = di.getAt(0);

                        if (daginfo != null)
                        {
                            var bs = Ext.data.StoreManager.lookup('Types_Banen_Store');
                            var baan = bs.getById(daginfo.data.BAAN_ID);

                            if (baan != null)
                            {
                                Ext.win.msg(sprintf("Baan %s", baan.data.OMSCHRIJVING));
                            }
                        }
                    }
                }
            });

        store = Ext.data.StoreManager.lookup('FlarmStart_Store');
        Ext.win.showLoading(true, store.storeId);
        store.load();

        store = Ext.data.StoreManager.lookup('AppSettings_Store');
        store.load();

        if (Ext.getCmp("ControleTab").isVisible())
        {
            Ext.data.StoreManager.lookup('ControleStartlijstFlarm_Store').load();
            Ext.data.StoreManager.lookup('ControleDagOverzicht_GridStore').load();
        }

    },

    onStarlijstDatumKeydown: function(textfield, e, eOpts) {
        Ext.Hoofdscherm.onStarlijstDatumKeydown(textfield, e, eOpts);
    },

    onWorkspaceAfterRender: function(component, eOpts) {
        var h = Ext.getCmp('Header');
        var de = Ext.getCmp('DatumExport');
        de.getEl().anchorTo(h.getEl(), 'tl', [160,30]);
    }

});