/*
 * File: app/model/Aanwezig_Leden_Model.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeZC_StartAdministratie.model.Aanwezig_Leden_Model', {
    extend: 'Ext.data.Model',

    idProperty: 'ID',

    fields: [
        {
            name: 'ID'
        },
        {
            name: 'LID_ID'
        },
        {
            name: 'NAAM'
        },
        {
            name: 'AANKOMST'
        },
        {
            name: 'VERTREK'
        },
        {
            name: 'ACTUELE_VLIEGTIJD'
        },
        {
            name: 'VOORKEUR_TYPE'
        },
        {
            name: 'VOORKEUR_REGCALL'
        },
        {
            name: 'INSTRUCTEUR'
        },
        {
            name: 'AANWEZIG'
        },
        {
            name: 'OPMERKING'
        },
        {
            name: 'LAATSTE_STARTTIJD'
        }
    ]
});