/*
 * File: app/model/AppSettings_Model.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeZC_StartAdministratie.model.AppSettings_Model', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'Aanwezigheid',
            type: 'boolean'
        },
        {
            name: 'ControleerPapieren',
            type: 'boolean'
        },
        {
            name: 'MagSchrijven',
            type: 'boolean'
        },
        {
            name: 'isBeheerder',
            type: 'boolean'
        },
        {
            name: 'isLocal',
            type: 'boolean'
        },
        {
            name: 'isBeheerderDDWV',
            type: 'boolean'
        },
        {
            name: 'ControleTolerantie',
            type: 'int'
        },
        {
            name: 'Betaald'
        }
    ]
});