/*
 * File: app/model/ControleStartlijstFlarm_Model.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeZC_StartAdministratie.model.ControleStartlijstFlarm_Model', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    idProperty: 'ID',

    fields: [
        {
            mapping: 'ID',
            name: 'ID'
        },
        {
            name: 'DAGNUMMER',
            type: 'int',
            useNull: true
        },
        {
            name: 'VLIEGTUIG_ID'
        },
        {
            name: 'SLEEPKIST_ID'
        },
        {
            name: 'STARTTIJD'
        },
        {
            name: 'LANDINGSTIJD'
        },
        {
            name: 'DUUR'
        },
        {
            name: 'OPMERKING'
        },
        {
            name: 'OP_REKENING_ID'
        },
        {
            name: 'VLIEGER_ID'
        },
        {
            name: 'VLIEGERNAAM_LID'
        },
        {
            name: 'VLIEGERNAAM'
        },
        {
            name: 'INZITTENDE_ID'
        },
        {
            name: 'INZITTENDENAAM_LID'
        },
        {
            name: 'INZITTENDENAAM'
        },
        {
            name: 'REG_CALL'
        },
        {
            name: 'STARTMETHODE'
        },
        {
            name: 'STARTMETHODE_ID'
        },
        {
            name: 'SOORTVLUCHT'
        },
        {
            name: 'SOORTVLUCHT_ID'
        },
        {
            name: 'LAATSTE_AANPASSING'
        },
        {
            name: 'FLARM_ID',
            type: 'int'
        },
        {
            name: 'FLARM_STARTTIJD'
        },
        {
            name: 'FLARM_LANDINGSTIJD'
        },
        {
            name: 'FLARM_CODE'
        },
        {
            name: 'FLARM_REG_CALL'
        },
        {
            name: 'FLARM_BAAN'
        },
        {
            name: 'dSTARTTIJD'
        },
        {
            name: 'dLANDINGSTIJD'
        },
        {
            name: 'WAARSCHUWING',
            type: 'boolean'
        }
    ]
});