/*
 * File: app/model/ControleStartlijstFlarm_Model.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeZC_StartAdministratie.model.ControleStartlijstFlarm_Model', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    idProperty: 'ID',

    fields: [
        {
            mapping: 'SA_ID',
            name: 'ID'
        },
        {
            name: 'DAGNUMMER',
            type: 'int',
            useNull: true
        },
        {
            name: 'SA_REG_CALL'
        },
        {
            name: 'SA_VLIEGERNAAM'
        },
        {
            name: 'SA_INZITTENDENAAM'
        },
        {
            name: 'SA_STARTTIJD'
        },
        {
            name: 'SA_LANDINGSTIJD'
        },
        {
            name: 'SA_DUUR'
        },
        {
            name: 'SA_SOORTVLUCHT'
        },
        {
            name: 'SA_STARTMETHODE'
        },
        {
            name: 'FLARM_ID',
            type: 'int'
        },
        {
            name: 'FLARM_STARTTIJD'
        },
        {
            name: 'FLARM_LANDINGSTIJD'
        },
        {
            name: 'FLARM_CODE'
        },
        {
            name: 'FLARM_REG_CALL'
        },
        {
            name: 'FLARM_BAAN'
        },
        {
            name: 'dSTARTTIJD'
        },
        {
            name: 'dLANDINGSTIJD'
        },
        {
            name: 'WAARSCHUWING',
            type: 'boolean'
        }
    ]
});