/*
 * File: app/model/ControleStartlijstTijdelijkeLeden_Model.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeZC_StartAdministratie.model.ControleStartlijstTijdelijkeLeden_Model', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    idProperty: 'ID',

    fields: [
        {
            name: 'ID'
        },
        {
            name: 'DATUM'
        },
        {
            name: 'DAGNUMMER'
        },
        {
            name: 'VLIEGTUIG_ID'
        },
        {
            name: 'SLEEPKIST_ID'
        },
        {
            name: 'STARTTIJD'
        },
        {
            name: 'LANDINGSTIJD'
        },
        {
            name: 'DUUR'
        },
        {
            name: 'OPMERKING'
        },
        {
            name: 'VLIEGER_ID'
        },
        {
            name: 'VLIEGERNAAM_LID'
        },
        {
            name: 'VLIEGERNAAM'
        },
        {
            name: 'INZITTENDE_ID'
        },
        {
            name: 'INZITTENDENAAM_LID'
        },
        {
            name: 'INZITTENDENAAM'
        },
        {
            name: 'REGISTRATIE'
        },
        {
            name: 'CALLSIGN'
        },
        {
            name: 'STARTMETHODE_ID'
        },
        {
            name: 'STARTMETHODE'
        },
        {
            name: 'SOORTVLUCHT_ID'
        },
        {
            name: 'SOORTVLUCHT'
        },
        {
            name: 'REG_CALL'
        },
        {
            name: 'OP_REKENING_ID'
        },
        {
            name: 'INZITTENDE_LIDTYPE_ID'
        },
        {
            name: 'VLIEGER_LIDTYPE_ID'
        },
        {
            name: 'LAATSTE_AANPASSING'
        }
    ]
});