/*
 * File: app/model/Daginfo_Model.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeZC_StartAdministratie.model.Daginfo_Model', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    idProperty: 'ID',

    fields: [
        {
            name: 'ID'
        },
        {
            name: 'DATUM'
        },
        {
            name: 'VELD_ID'
        },
        {
            name: 'BAAN_ID'
        },
        {
            name: 'WINDRICHTING_ID'
        },
        {
            name: 'WINDKRACHT_ID'
        },
        {
            name: 'BEDRIJF_ID'
        },
        {
            name: 'SOORTBEDRIJF_ID'
        },
        {
            name: 'STARTMETHODE_ID'
        },
        {
            name: 'OCHTEND_DDI'
        },
        {
            name: 'OCHTEND_INSTRUCTEUR'
        },
        {
            name: 'OCHTEND_LIERIST'
        },
        {
            name: 'OCHTEND_HULPLIERIST'
        },
        {
            name: 'OCHTEND_STARTLEIDER'
        },
        {
            name: 'MIDDAG_DDI'
        },
        {
            name: 'MIDDAG_INSTRUCTEUR'
        },
        {
            name: 'MIDDAG_LIERIST'
        },
        {
            name: 'MIDDAG_HULPLIERIST'
        },
        {
            name: 'MIDDAG_STARTLEIDER'
        },
        {
            name: 'OPMERKINGEN'
        },
        {
            name: 'ROOSTER'
        }
    ]
});