/*
 * File: app/model/FlarmPositie_Model.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeZC_StartAdministratie.model.FlarmPositie_Model', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    idProperty: 'FLARM_CODE',

    fields: [
        {
            name: 'FLARM_CODE',
            type: 'string'
        },
        {
            name: 'REG_CALL'
        },
        {
            name: 'LATITUDE',
            type: 'float'
        },
        {
            name: 'LONGITUDE',
            type: 'float'
        },
        {
            name: 'SPEED'
        },
        {
            name: 'ALTITUDE'
        },
        {
            name: 'ROC'
        },
        {
            name: 'VERTICAL',
            type: 'float'
        },
        {
            name: 'LAST_RECEIVED',
            type: 'date'
        },
        {
            name: 'CALLSIGN'
        },
        {
            name: 'VLIEGT',
            type: 'boolean'
        }
    ]
});