/*
 * File: app/model/FlarmStart_Model.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeZC_StartAdministratie.model.FlarmStart_Model', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    idProperty: 'ID',

    fields: [
        {
            name: 'ID'
        },
        {
            name: 'DATUM'
        },
        {
            name: 'REG_CALL'
        },
        {
            name: 'FLARM_CODE'
        },
        {
            name: 'STARTTIJD'
        },
        {
            name: 'LANDINGSTIJD'
        },
        {
            name: 'VLIEGTUIG_ID'
        },
        {
            name: 'BAAN'
        }
    ]
});